### ISSUE TITLE
Parameter scan

### ISSUE THREAD

**Issue by fiedl** [fiedl/hole-ice-study#12]
We do not know the actual ice properties of the hole ice, yet.

How do the angular acceptance plots look like for different hole ice parameters?

- [x] [Import script](https://github.com/fiedl/hole-ice-study/commit/cb0b779033e55c7d593b8d5d6351718b54192668).
- [ ] Document script.
- [x] [Parallelise such that it can run as array job on the cluster](https://github.com/fiedl/hole-ice-study/commit/fcec940f59c96e2c44aa561f4192ff968ff6c43e).
- [x] [Run rough scan on the cluster](https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376609490).
- [x] Run detailed scan on the best region of the parameter space. -> *[Run a with better resolution and more photons](https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-406721082)*.
- [x] [Run detailed scan on the region of Martin's best parameters](https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376872558).
- [x] [Run a with better resolution and more photons](
https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-406721082).
- [x] [Plot results](
https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-406800988).
- [ ] Document results in README.

### [Results](https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-406800988)

```bash
[2018-07-21 16:38:53] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_reference_curve_scan_contours.py ~/hole-ice-study/results/parameter_scan
best values:
  LLH: -633.315809421
  esca = 1.3m
  r = 1.0 r_dom
```

![bildschirmfoto 2018-07-21 um 16 40 09](https://user-images.githubusercontent.com/1679688/43036596-0851521e-8d05-11e8-8272-304e52e72ee0.png)

```
[2018-07-21 16:44:04] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca1.0_r1.0rdom_abs100
```

![bildschirmfoto 2018-07-21 um 16 45 25](https://user-images.githubusercontent.com/1679688/43036632-8561c7f2-8d05-11e8-81f8-d523e13773a8.png)

**Comment by fiedl** [comment]
### Single test run on the cluster

```bash
[2018-03-12 15:29:08] fiedl@wgs16 /afs/ifh.de/group/amanda/scratch/fiedl/hole-ice-study master ⚡
▶ git pull

[2018-03-12 15:29:21] fiedl@wgs16 /afs/ifh.de/group/amanda/scratch/fiedl/clsim sf/hole-ice-2018
▶ git pull

[2018-03-12 15:29:50] fiedl@wgs16 /afs/ifh.de/group/amanda/scratch/fiedl/software/icecube-simulation-V05-00-07/debug_build
▶ ./env-shell.sh

[2018-03-12 15:30:46] fiedl@wgs16 /afs/ifh.de/group/amanda/scratch/fiedl/software/icecube-simulation-V05-00-07/debug_build/clsim
▶ make

[2018-03-12 15:36:21] fiedl@wgs16 /afs/ifh.de/group/amanda/scratch/fiedl/hole-ice-study/scripts/ParameterScan master ⚡
▶ ./run.rb --submit-to-cluster
```

**Comment by fiedl** [comment]
Best parameter set of this scan: 

![plot_with_reference](https://user-images.githubusercontent.com/1679688/37313873-6ff5c208-2651-11e8-91a2-bcd19d67c0ee.png)

```ruby
{:cluster=>true,
 :distance=>1.0,
 :plane_wave=>true,
 :number_of_photons=>100000.0,
 :number_of_runs=>2.0,
 :number_of_parallel_runs=>2.0,
 :angles=>[0, 10, 20, 30, 40, 50, 60, 70, 90, 120, 140, 150, 160, 170, 180],
 :run_id=>"Run-2018-daeph4pi",
 :started_at=>"2018-03-12 16:59:25 +0100",
 :gcd_file=>
  "$I3_TESTDATA/sim/GeoCalibDetectorStatus_IC86.55380_corrected.i3.gz",
 :ice_model_file=>"$I3_SRC/clsim/resources/ice/spice_mie",
 :seed=>123456,
 :hole_ice_cylinder_positions=>[[-256.02301025390625, -521.281982421875, 0]],
 :hole_ice_cylinder_radii=>[0.3],
 :cylinder_scattering_lengths=>[0.178],
 :cylinder_absorption_lengths=>[100.0],
 :gcd_file_with_hole_ice=>"tmp/gcd_with_hole_ice.i3",
 :create_gcd_log=>"tmp/create_gcd_with_hole_ice.log",
 :dom_index=>[1, 1],
 :dom_position=>[-256.02301025390625, -521.281982421875, 500],
 :hole_ice=>:simulation,
 :save_photon_paths=>false,
 :propagation_log_file=>"tmp/propagation.log",
 :clsim_error_fallback=>"skip",
 :propagation_finished_at=>"2018-03-12 17:15:17 +0100",
 # ...
}
```

**Comment by fiedl** [comment]
best fit to reference plot:

![plot_with_reference](https://user-images.githubusercontent.com/1679688/37401481-71341470-2788-11e8-8ab2-20686be35298.png)

```ruby
{:cluster=>true,
 :hole_ice_scattering_length=>0.09000000000000008,
 :hole_ice_absorption_length=>100.0,
 :hole_ice_radius=>0.1651,
 :distance=>1.0,
 :plane_wave=>true,
 :number_of_photons=>100000.0,
 :number_of_runs=>2.0,
 :number_of_parallel_runs=>2.0,
 :angles=>[0, 10, 20, 30, 40, 50, 60, 70, 90, 120, 140, 150, 160, 170, 180],
 :run_id=>"Run-2018-hiHoh7uf",
 :started_at=>"2018-03-13 23:34:34 +0100",
 :gcd_file=>
  "$I3_TESTDATA/sim/GeoCalibDetectorStatus_IC86.55380_corrected.i3.gz",
 :ice_model_file=>"$I3_SRC/clsim/resources/ice/spice_mie",
 :seed=>123456,
 :hole_ice_cylinder_positions=>[[-256.02301025390625, -521.281982421875, 0]],
 :hole_ice_cylinder_radii=>[0.1651],
 :cylinder_scattering_lengths=>[0.09000000000000008],
 :cylinder_absorption_lengths=>[100.0],
 :hole_ice_radius_in_dom_radii=>1.0,
 :hole_ice_effective_scattering_length=>1.5,
 :dom_index=>[1, 1],
 :dom_position=>[-256.02301025390625, -521.281982421875, 500],
 :hole_ice=>:simulation,
 # ...
}
```

**Comment by fiedl** [comment]
Contour plot (https://github.com/fiedl/hole-ice-study/issues/37) of parameter scan agreements with reference plot (https://github.com/fiedl/hole-ice-study/issues/10, https://github.com/fiedl/hole-ice-study/issues/6)

![bildschirmfoto 2018-03-14 um 15 02 48](https://user-images.githubusercontent.com/1679688/37407054-0ba0f0b8-2799-11e8-8b97-3843aece6320.png)

**Comment by fiedl** [comment]
### Simulation performance

For each parameter set, 30e5 photons are propagated (1e5 photons per run, 2 runs per angle, 15 angles).

![bildschirmfoto 2018-03-15 um 15 59 29](https://user-images.githubusercontent.com/1679688/37471442-fe491e64-2869-11e8-96f3-70a5280f4212.png)

**Comment by fiedl** [comment]
### Another likelihood measure

See notes: 2018-03-16.

![bildschirmfoto 2018-03-26 um 16 11 57](https://user-images.githubusercontent.com/1679688/37911465-6e406f3e-3110-11e8-86cc-c24b76d8d553.png)

(https://en.wikipedia.org/wiki/Binomial_coefficient#Binomial_coefficient_in_programming_languages)

**Comment by fiedl** [comment]
### Gauging

<img width="693" alt="bildschirmfoto 2018-03-27 um 18 02 19" src="https://user-images.githubusercontent.com/1679688/37979497-0a37602c-31e9-11e8-974f-18c7bb8972a4.png">

**Comment by fiedl** [comment]
### Contour plot

Contour plot (https://github.com/fiedl/hole-ice-study/issues/37) of parameter scan agreements with reference plot (https://github.com/fiedl/hole-ice-study/issues/10, https://github.com/fiedl/hole-ice-study/issues/6) with new **likelihood function** (https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376179961) and gauging parameter (https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376580354):

<img width="579" alt="bildschirmfoto 2018-03-27 um 19 25 40" src="https://user-images.githubusercontent.com/1679688/37984064-837365e2-31f5-11e8-85d8-f07f0c0190ff.png">

**Comment by fiedl** [comment]
### Contour plot of the detail scan

```bash
[2018-03-28 14:48:59] fiedl@fiedl-mbp ~/hole-ice-study/scripts/AngularAcceptance master ⚡
▶ lib/plot.rb ~/hole-ice-study/results/2018-03-15_parameter_detail_scan
```

![bildschirmfoto 2018-03-28 um 14 59 34](https://user-images.githubusercontent.com/1679688/38030506-1a3058ca-3299-11e8-8cb5-04a6d5fc2141.png)

The best parameters appear to be:

- effective scattering length: 0.2m
- hole-ice radius: 0.8 dom radii

But the agreement is worse than for the previous scan area: https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376609490

The angular-acceptance plot of the best-parameter run does confirm this: It does look rather bad.

![plot_with_reference](https://user-images.githubusercontent.com/1679688/38030651-76bba75c-3299-11e8-804a-fb14bfd769dd.png)

This suggests that the parameter area of Martin's best parameters is not in agreement with the hole-ice approximation used in current clsim.

**Comment by fiedl** [comment]
### Detailed scan of region with best agreement to reference curve

Contour plot of the rough scan: https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376609490

Best region:

- effective scattering length: 0.6m to 2.2m
- hole-ice radius: 0.8 to 1.7 dom radii

Configuration:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.6..2.2).step(0.05).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.8..1.7).step(0.1).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e5,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

**Comment by fiedl** [comment]
### Results of the detailed scan of the region with best agreement to the reference curve

```bash
[2018-03-28 19:45:09] fiedl@fiedl-mbp ~/hole-ice-study/scripts/AngularAcceptance master ⚡
▶ lib/plot.rb ~/hole-ice-study/results/parameter_detail_scan_of_best_agreement_region
```

![bildschirmfoto 2018-03-28 um 19 51 47](https://user-images.githubusercontent.com/1679688/38047126-cf4d4b3c-32c1-11e8-9e35-8c93f02766a2.png)

It almost looks like they've just used 1m effective scattering length and 1 dom radius as hole-ice radius to generate the reference curve.

Best agreement:

```bash
[2018-03-28 19:51:58] fiedl@fiedl-mbp ~/hole-ice-study/scripts/AngularAcceptance master ⚡
▶ open ~/hole-ice-study/results/parameter_detail_scan_of_best_agreement_region/./esca1.15_r1.0rdom_abs100/data/plot_with_reference.png
```

![plot_with_reference](https://user-images.githubusercontent.com/1679688/38047145-d898a2ea-32c1-11e8-9e47-57a3c579da6f.png)

1-1 result:

```bash
[2018-03-28 19:52:51] fiedl@fiedl-mbp ~/hole-ice-study/scripts/AngularAcceptance master ⚡
▶ open ~/hole-ice-study/results/parameter_detail_scan_of_best_agreement_region/esca1.0_r1.0rdom_abs100/data/plot_with_reference.png
```

![plot_with_reference](https://user-images.githubusercontent.com/1679688/38047316-658038f8-32c2-11e8-982a-2b25658dc0c1.png)

Note that the error bars in these plots still use the chi-squared agreement rather than the new likelihood. I.e. they falsely assume a gaussian distribution.

**Comment by fiedl** [comment]
### Parameter scan with pencil beam rather than plane waves

Same configuration of the detailed-scan area:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.6..2.2).step(0.05).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.8..1.7).step(0.1).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e5,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

But without `--plane-wave` switch.

**Comment by fiedl** [comment]
### Parameter scan with pencil beam rather than plane waves

Same configuration of the detailed-scan area:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.6..2.2).step(0.05).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.8..1.7).step(0.1).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e5,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

But without `--plane-wave` switch.

**Comment by fiedl** [comment]
### Parameter scan with pencil beam for wider region

Same region as: https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376609490

Configuration:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.5..3.5).step(0.5).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.5..2.5).step(0.5).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e5,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

**Comment by fiedl** [comment]
### Parameter scan with pencil beam for wider parameter region

Same region as: https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376609490

Configuration:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.5..3.5).step(0.5).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.5..2.5).step(0.5).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e5,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

**Comment by fiedl** [comment]
### Parameter scan with less photons

Repeat scan https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376910272 with less photons (1e4 rather than 1e5 per run and angle). What effect does this have on the contour plot?

Configuration:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.6..2.2).step(0.05).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.8..1.7).step(0.1).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e4,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

Submission

Results

Plot

**Comment by fiedl** [comment]
### Signa contours

I would like to create a plot like this for the parameter scan:
https://wiki.icecube.wisc.edu/index.php/File:8yr_diffuse_numu_scan_astro_cutoff_fix_bestfit_.png

**Comment by fiedl** [comment]
### Parameter scan with less photons

Repeat scan https://github.com/fiedl/hole-ice-study/issues/12#issuecomment-376910272 with less photons (1e4 rather than 1e5 per run and angle). What effect does this have on the contour plot?

Configuration:

```ruby
  # Parameter range configuration
  #
  options.merge!({
    effective_scattering_length_range: (0.6..2.2).step(0.05).to_a.collect { |x| x.round(2) },
    hole_ice_radius_range_in_dom_radii: (0.8..1.7).step(0.1).to_a.collect { |x| x.round(2) },
    absorption_length_range: [100],
    distance_range: [1.0],
    number_of_photons: 1e4,
    number_of_runs: 2,
    number_of_parallel_runs: 2,
    angles: [0,10,20,30,40,50,60,70,90,120,140,150,160,170,180]
  })
  dom_radius = 0.16510
  mean_scattering_angle_cosine = 0.94
  options.merge!({
    scattering_length_range: options[:effective_scattering_length_range].collect { |s| s * ( 1 - 0.94) },
    hole_ice_radius_range: options[:hole_ice_radius_range_in_dom_radii].collect { |n| n * dom_radius }
  })
```

Submission

Results

Gauging

Plot

**Comment by fiedl** [comment]
## Comparing contour plots with shared color bar

**Comment by fiedl** [comment]
### Comparing contour plots with shared color bar

```bash
[2018-04-11 17:07:25] fiedl@fiedl-mbp ~/hole-ice-study/scripts/AngularAcceptance master ⚡
▶ lib/plot.rb ~/hole-ice-study/results/parameter_scan_of_best_agreement_region_with_less_photons_plane_waves ~/hole-ice-study/results/parameter_detail_scan_of_best_agreement_region

▶ python lib/create_contour_plot.py ~/hole-ice-study/results/parameter_scan_of_best_agreement_region_with_less_photons_plane_waves/parameter_scan_agreements.txt ~/hole-ice-study/results/parameter_detail_scan_of_best_agreement_region/parameter_scan_agreements.txt
```

![bildschirmfoto 2018-04-11 um 17 39 22](https://user-images.githubusercontent.com/1679688/38627911-5dc015c2-3db0-11e8-8794-6fd972accc1c.png)

**Comment by fiedl** [comment]
## Another scan

After performance optimizations, I'm starting another parameter scan.

**Comment by fiedl** [comment]
```bash
[2018-07-20 16:07:48] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./convert_options_txt_to_json.rb ~/hole-ice-study/results/parameter_scan
▶ ./calculate_reference_plot_llhs.py ~/hole-ice-study/results/parameter_scan
```

**Comment by fiedl** [comment]
```bash
[2018-07-20 16:19:41] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_reference_curve_scan_contours.py ~/hole-ice-study/results/parameter_scan
best values:
  LLH: -105.810004396
  esca = 1.0m
  r = 1.0 r_dom
```

**Comment by fiedl** [comment]
Best agreement:

```bash
[2018-07-20 16:34:12] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca1.0_r1.0rdom
```

![bildschirmfoto 2018-07-20 um 16 36 00](https://user-images.githubusercontent.com/1679688/43008334-1556821a-8c3b-11e8-94da-ec38c22c34d8.png)

**Comment by fiedl** [comment]
bottom right corner: strong hole ice

```bash
[2018-07-20 16:37:31] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca0.2_r1.8rdom_abs100
```

![bildschirmfoto 2018-07-20 um 16 38 56](https://user-images.githubusercontent.com/1679688/43008448-6b9a24e2-8c3b-11e8-933c-c5643609957b.png)

**Comment by fiedl** [comment]
top left corner: weak hole ice

```bash
[2018-07-20 16:39:04] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca3.0_r0.1rdom
```

![bildschirmfoto 2018-07-20 um 16 40 32](https://user-images.githubusercontent.com/1679688/43008549-af570ce0-8c3b-11e8-8371-23fad1ce8a7e.png)

**Comment by fiedl** [comment]
upper right: when increasing the radius while increasing the scattering length, one effect strengthens while the other weakens the hole-ice effect. Thus, this is still a good agreement:

```bash
[2018-07-20 16:40:45] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca2.8_r1.5rdom_abs100
```

![bildschirmfoto 2018-07-20 um 16 42 27](https://user-images.githubusercontent.com/1679688/43008738-18b7d8b8-8c3c-11e8-974a-71789535c5df.png)

**Comment by fiedl** [comment]
```bash
[2018-07-20 22:38:09] fiedl@kepler00 /afs/ifh.de/group/amanda/scratch/fiedl/hole-ice-study/scripts/ParameterScan
▶ git pull
▶ ./run.rb --submit-to-cluster
```

**Comment by fiedl** [comment]
```bash
[2018-07-21 16:36:20] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./convert_options_txt_to_json.rb ~/hole-ice-study/results/parameter_scan
▶ ./calculate_reference_plot_llhs.py ~/hole-ice-study/results/parameter_scan
```

**Comment by fiedl** [comment]
```bash
[2018-07-21 16:38:53] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_reference_curve_scan_contours.py ~/hole-ice-study/results/parameter_scan
best values:
  LLH: -633.315809421
  esca = 1.3m
  r = 1.0 r_dom
```

![bildschirmfoto 2018-07-21 um 16 40 09](https://user-images.githubusercontent.com/1679688/43036596-0851521e-8d05-11e8-8272-304e52e72ee0.png)

**Comment by fiedl** [comment]
Best agreement:

```
[2018-07-21 16:40:21] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca1.3_r1.0rdom_abs100
```

![bildschirmfoto 2018-07-21 um 16 43 52](https://user-images.githubusercontent.com/1679688/43036610-566d63f2-8d05-11e8-939b-c35fe9261267.png)

**Comment by fiedl** [comment]
bottom right corner: strong hole ice

```
[2018-07-21 16:45:31] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca0.2_r1.8rdom_abs100
```

![bildschirmfoto 2018-07-21 um 17 14 23](https://user-images.githubusercontent.com/1679688/43037102-963072aa-8d09-11e8-8905-299756888a77.png)

**Comment by fiedl** [comment]
top left corner: weak hole ice

```
[2018-07-21 17:16:31] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca3.0_r0.1rdom_abs100/
```

![bildschirmfoto 2018-07-21 um 17 17 20](https://user-images.githubusercontent.com/1679688/43037126-f39d03f4-8d09-11e8-8039-85d650a9f1e6.png)

**Comment by fiedl** [comment]
upper right: when increasing the radius while increasing the scattering length, one effect strengthens while the other weakens the hole-ice effect. Thus, this is still a good agreement:

```
[2018-07-21 17:17:30] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_angular_acceptance.py ../../results/parameter_scan/esca2.8_r1.5rdom_abs100
```

![bildschirmfoto 2018-07-21 um 17 18 35](https://user-images.githubusercontent.com/1679688/43037138-2649357a-8d0a-11e8-843e-a8f6ce83c39c.png)

**Comment by fiedl** [comment]
## Another scan with pencil beam

As performance is now good, I'm retrying the pencil-beam scan.

**Comment by fiedl** [comment]
```bash
[2018-07-21 18:56:19] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./convert_options_txt_to_json.rb ../../results/parameter_scan_pencil_beam
▶ ./calculate_reference_plot_llhs.py ../../results/parameter_scan_pencil_beam
```

**Comment by fiedl** [comment]
```bash
[2018-07-21 19:00:51] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./plot_reference_curve_scan_contours.py ~/hole-ice-study/results/parameter_scan_pencil_beam
best values:
  LLH: -5575.61508961
  esca = 3.5m
  r = 2.5 r_dom
```

![bildschirmfoto 2018-07-21 um 19 03 33](https://user-images.githubusercontent.com/1679688/43038436-d0fd6dd4-8d18-11e8-8d42-0c40af21eabb.png)

Best values:

![bildschirmfoto 2018-07-21 um 19 07 15](https://user-images.githubusercontent.com/1679688/43038468-5575ab26-8d19-11e8-8b5a-7ac0445d6f03.png)

**Comment by fiedl** [comment]
## Starting photons from farther away

```bash
[2018-07-24 15:41:35] fiedl@trex01 /afs/ifh.de/group/amanda/scratch/fiedl/hole-ice-study/scripts/AngularAcceptance
▶ ./run.rb --cluster --hole-ice-scattering-length=0.06 --hole-ice-radius=0.1651 --distance=2.0 --number-of-photons=1e6 --number-of-runs=1 --number-of-parallel-runs=1 --angles=0,10,20,30,40,50,60,70,90,120,140,150,160,170,180 --plane-wave
```

**Comment by fiedl** [comment]
```bash
[2018-07-24 16:06:33] fiedl@fiedl-mbp ~/hole-ice-study/scripts/lib master ⚡
▶ ./convert_options_txt_to_json.rb ../AngularAcceptance/results/current
▶ ./plot_angular_acceptance.py ../AngularAcceptance/results/current
```

![bildschirmfoto 2018-07-24 um 16 08 26](https://user-images.githubusercontent.com/1679688/43143743-d162c112-8f5b-11e8-97e1-49fda417015e.png)

One would need another gauging simulation. But this plot already shows that on the left-hand side there are still too many hits.
